
# the webserver requires a restart in order to apply changes of the configuration

# color theme of the webpage
# possible strings: dark, light, debug
theme: dark

# directories of movies
# possible strings: [absolute path]
# (multiple values allowed)
movie-directories:
  - N:\\Videos\\Filme-Sammlung_1
  - N:\\Videos\\Filme-Sammlung_2

# directories to search for associated metadata files of the movies
# possible strings: [absolute path]
# note: must be in the same order as the 'movie-directories' entries
#       e.g. the first directory of the 'metadata-directories' contains the metadata yaml files for the movies in the first directory of the 'movie-directories'
# (multiple values allowed)
metadata-directories:
  - N:\\Videos\\Filme-Sammlung_1\\data
  - N:\\Videos\\Filme-Sammlung_2

# length of title displayed in movie overview
# possible integers: >= 0
# note: use 0 to not limit the length of the title
title-length: 0

# filters that are applied to movie elements not included in the search results
# possible strings: unclickable, hidden, blurred, grayed, darkened, inverted, faded, cleared
# (multiple values allowed)
not-result-filters:
  - blurred
  - faded
  - unclickable

# webpage icon
# possible strings: [path relative to 'static/images/']
favicon: favicon.png

# port of webserver, where the webpage is available
# possible integers: 80, >=1025
server-port: 80

# host added by the installation script to dns resolver
server-name: filmbibliothek

# makes the local webserver accessible in your (local) network
# to reach the website on a different device in the same network, use the local ip address of the host device
# possible values: true, false
accessible-in-network: true

# minimum level of logging messages
# possible strings: DEBUG, INFO, WARNING, ERROR, CRITICAL
log-level: WARNING
